const vocabulary = {
    A1: {
        nouns: {
            'pige': { en: 'girl', example: 'Pigen spiser et æble.', translated: 'The girl is eating an apple.' },
            'dreng': { en: 'boy', example: 'Drengen læser en bog.', translated: 'The boy is reading a book.' },
            'hus': { et: 'house', example: 'Huset er stort.', translated: 'The house is big.' },
            'bog': { en: 'book', example: 'Jeg har en bog.', translated: 'I have a book.' },
            'æble': { et: 'apple', example: 'Æblet er rødt.', translated: 'The apple is red.' },
            'familie': { en: 'family', example: 'Min familie er glad.', translated: 'My family is happy.' },
            'ven': { en: 'friend', example: 'Han er en god ven.', translated: 'He is a good friend.' },
            'skole': { en: 'school', example: 'Hun går i skole.', translated: 'She goes to school.' },
            'mad': { en: 'food', example: 'Maden er god.', translated: 'The food is good.' },
            'vand': { et: 'water', example: 'Jeg drikker vand.', translated: 'I drink water.' },
            'banan': { en: 'banana', example: 'Jeg spiser en stor banan.', translated: 'I am eating a big banana.' },
            'hund': { en: 'dog', example: 'Hunden er sød.', translated: 'The dog is cute.' },
            'kat': { en: 'cat', example: 'Katten sover.', translated: 'The cat is sleeping.' },
            'bord': { et: 'table', example: 'Bogen ligger på bordet.', translated: 'The book is on the table.' },
            'stol': { en: 'chair', example: 'Jeg sidder på en stol.', translated: 'I am sitting on a chair.' },
            'sko': { en: 'shoe', example: 'Mine sko er nye.', translated: 'My shoes are new.' },
            'kaffe': { en: 'coffee', example: 'Jeg drikker kaffe om morgenen.', translated: 'I drink coffee in the morning.' },
            'te': { en: 'tea', example: 'Vil du have te?', translated: 'Do you want tea?' },
            'mælk': { en: 'milk', example: 'Mælken er kold.', translated: 'The milk is cold.' },
            'brød': { et: 'bread', example: 'Vi spiser brød til morgenmad.', translated: 'We eat bread for breakfast.' },
            'ost': { en: 'cheese', example: 'Jeg kan lide ost.', translated: 'I like cheese.' },
            'dør': { en: 'door', example: 'Døren er åben.', translated: 'The door is open.' },
            'vindue': { et: 'window', example: 'Vinduet er lukket.', translated: 'The window is closed.' },
            'vej': { en: 'road', example: 'Vi går på vejen.', translated: 'We are walking on the road.' },
            'by': { en: 'city', example: 'Jeg bor i en stor by.', translated: 'I live in a big city.' },
            'land': { et: 'country', example: 'Danmark er et smukt land.', translated: 'Denmark is a beautiful country.' },
            'dag': { en: 'day', example: 'I dag er en god dag.', translated: 'Today is a good day.' },
            'nat': { en: 'night', example: 'God nat!', translated: 'Good night!' },
            'tid': { en: 'time', example: 'Jeg har ikke tid.', translated: 'I don\'t have time.' }
        },
        verbs: {
            'spise': { en: 'to eat', example: 'De spiser mad.', translated: 'They are eating food.', conjugations: { present: 'spiser', past: 'spiste', perfect: 'spist' } },
            'læse': { en: 'to read', example: 'Vi læser en bog.', translated: 'We are reading a book.', conjugations: { present: 'læser', past: 'læste', perfect: 'læst' } },
            'se': { en: 'to see', example: 'Jeg ser en bil.', translated: 'I see a car.', conjugations: { present: 'ser', past: 'så', perfect: 'set' } },
            'have': { en: 'to have', example: 'Hun har een stor bil.', translated: 'She has a big car.', conjugations: { present: 'har', past: 'havde', perfect: 'haft' } },
            'være': { en: 'to be', example: 'Vi er glade.', translated: 'We are happy.', conjugations: { present: 'er', past: 'var', perfect: 'været' } },
            'hedde': { en: 'to be called', example: 'Jeg hedder Peter.', translated: 'I am called Peter.', conjugations: { present: 'hedder', past: 'hed', perfect: 'heddet' } },
            'komme': { en: 'to come', example: 'Han kommer fra Danmark.', translated: 'He comes from Denmark.', conjugations: { present: 'kommer', past: 'kom', perfect: 'kommet' } },
            'bo': { en: 'to live', example: 'De bor i et hus.', translated: 'They live in a house.', conjugations: { present: 'bor', past: 'boede', perfect: 'boet' } },
            'kunne': { en: 'can', example: 'Jeg kan tale dansk.', translated: 'I can speak Danish.', conjugations: { present: 'kan', past: 'kunne', perfect: 'kunnet' } },
            'ville': { en: 'will', example: 'Jeg vil gerne have kaffe.', translated: 'I would like to have coffee.', conjugations: { present: 'vil', past: 'ville', perfect: 'villet' } },
            'skulle': { en: 'must/shall', example: 'Du skal sove nu.', translated: 'You must sleep now.', conjugations: { present: 'skal', past: 'skulle', perfect: 'skullet' } },
            'måtte': { en: 'may/must', example: 'Du må ikke spise kage.', translated: 'You must not eat cake.', conjugations: { present: 'må', past: 'måtte', perfect: 'måttet' } },
            'vide': { en: 'to know', example: 'Jeg ved ikke.', translated: 'I don\'t know.', conjugations: { present: 'ved', past: 'vidste', perfect: 'vidst' } },
            'tage': { en: 'to take', example: 'Jeg tager bussen.', translated: 'I take the bus.', conjugations: { present: 'tager', past: 'tog', perfect: 'taget' } },
            'give': { en: 'to give', example: 'Han giver mig en bog.', translated: 'He gives me a book.', conjugations: { present: 'giver', past: 'gav', perfect: 'givet' } },
            'finde': { en: 'to find', example: 'Jeg kan ikke finde mine nøgler.', translated: 'I cannot find my keys.', conjugations: { present: 'finder', past: 'fandt', perfect: 'fundet' } },
            'tale': { en: 'to speak/talk', example: 'Jeg taler dansk.', translated: 'I speak Danish.', conjugations: { present: 'taler', past: 'talte', perfect: 'talt' } },
            'forstå': { en: 'to understand', example: 'Forstår du det?', translated: 'Do you understand it?', conjugations: { present: 'forstår', past: 'forstod', perfect: 'forstået' } },
            'kende': { en: 'to know (person/place)', example: 'Jeg kender ham godt.', translated: 'I know him well.', conjugations: { present: 'kender', past: 'kendte', perfect: 'kendt' } },
            'elske': { en: 'to love', example: 'Jeg elsker min familie.', translated: 'I love my family.', conjugations: { present: 'elsker', past: 'elskede', perfect: 'elsket' } }
        },
        adjectives: {
            'stor': { en: 'big', example: 'Huset er stort.', translated: 'The house is big.' },
            'lille': { en: 'small', example: 'Jeg ser en lille pige.', translated: 'I see a small girl.' },
            'rød': { en: 'red', example: 'Æblet er rødt.', translated: 'The apple is red.' },
            'god': { en: 'good', example: 'Det er en god dag.', translated: 'It is a good day.' },
            'glad': { en: 'happy', example: 'Vi er glade.', translated: 'We are happy.' },
            'ny': { en: 'new', example: 'Mine sko er nye.', translated: 'My shoes are new.' },
            'gammel': { en: 'old', example: 'Min bil er gammel.', translated: 'My car is old.' }
        },
        other: {
            'min': { en: 'my', example: 'Min familie er glad.', translated: 'My family is happy.' },
            'jeg': { en: 'I', example: 'Jeg er glad.', translated: 'I am happy.' },
            'du': { en: 'you', example: 'Du spiser en kage.', translated: 'You are eating a cake.' },
            'han': { en: 'he', example: 'Han kommer fra København.', translated: 'He comes from Copenhagen.' },
            'hun': { en: 'she', example: 'Hun er min ven.', translated: 'She is my friend.' },
            'vi': { en: 'we', example: 'Vi har en kat.', translated: 'We have a cat.' },
            'de': { en: 'they', example: 'De læser i bogen.', translated: 'They are reading the book.' },
            'hvad': { en: 'what', example: 'Hvad spiser du?', translated: 'What are you eating?' },
            'hvor': { en: 'where', example: 'Hvor bor du?', translated: 'Where do you live?' },
            'og': { en: 'and', example: 'Han og hun er glade.', translated: 'He and she are happy.' },
            'i': { en: 'in', example: 'Jeg bor i Danmark.', translated: 'I live in Denmark.' },
            'på': { en: 'on', example: 'Bogen ligger på bordet.', translated: 'The book is on the table.' },
            'ikke': { en: 'not', example: 'Jeg er ikke glad.', translated: 'I am not happy.' },
            'en': { en: 'a', example: 'Jeg spiser en banan.', translated: 'I am eating a banana.' },
            'et': { en: 'a', example: 'Jeg har et hus.', translated: 'I have a house.' },
            'til': { en: 'to', example: 'Jeg går til skole.', translated: 'I walk to school.' },
            'fra': { en: 'from', example: 'Han kommer fra Danmark.', translated: 'He comes from Denmark.' },
            'med': { en: 'with', example: 'Jeg spiser med en gaffel.', translated: 'I eat with a fork.' },
            'af': { en: 'of/by', example: 'Bogen er skrevet af ham.', translated: 'The book is written by him.' },
            'som': { en: 'as/like', example: 'Jeg arbejder som lærer.', translated: 'I work as a teacher.' }
        }
    },
    A2: {
        nouns: {
            'bil': { en: 'car', example: 'Min bil er gammel.', translated: 'My car is old.' },
            'arbejde': { et: 'work', example: 'Jeg har meget arbejde.', translated: 'I have a lot of work.' },
            'fritid': { en: 'leisure time', example: 'I min fritid læser jeg.', translated: 'In my leisure time I read.' },
            'butik': { en: 'shop', example: 'Butikken er lukket.', translated: 'The shop is closed.' },
            'penge': { en: 'money', example: 'Jeg har mange penge.', translated: 'I have a lot of money.' },
            'vejr': { et: 'weather', example: 'Vejret er koldt.', translated: 'The weather is cold.' },
            'rejse': { en: 'journey', example: 'Vi tager på en rejse.', translated: 'We are going on a trip.' },
            'sprog': { et: 'language', example: 'Dansk er et sprog.', translated: 'Danish is a language.' },
            'uge': { en: 'week', example: 'Ugen har syv dage.', translated: 'The week has seven days.' }
        },
        verbs: {
            'køre': { en: 'to drive', example: 'Han kører bil.', translated: 'He is driving a car.', conjugations: { present: 'kører', past: 'kørte', perfect: 'kørt' } },
            'arbejde': { en: 'to work', example: 'Jeg arbejder på en butik.', translated: 'I work at a shop.', conjugations: { present: 'arbejder', past: 'arbejdede', perfect: 'arbejdet' } },
            'besøge': { en: 'to visit', example: 'De besøger deres familie.', translated: 'They are visiting their family.', conjugations: { present: 'besøger', past: 'besøgte', perfect: 'besøgt' } },
            'lave': { en: 'to make', example: 'Hun laver mad.', translated: 'She is making food.', conjugations: { present: 'laver', past: 'lavede', perfect: 'lavet' } },
            'købe': { en: 'to buy', example: 'Jeg køber en ny bil.', translated: 'I am buying a new car.', conjugations: { present: 'køber', past: 'købte', perfect: 'købt' } },
            'synes': { en: 'to think/find', example: 'Jeg synes det er smukt.', translated: 'I think it is beautiful.', conjugations: { present: 'synes', past: 'syntes', perfect: 'syntes' } },
            'hjælpe': { en: 'to help', example: 'Vi hjælper hinanden.', translated: 'We are helping each other.', conjugations: { present: 'hjælper', past: 'hjalp', perfect: 'hjulpet' } },
            'sælge': { en: 'to sell', example: 'Han sælger sin bil.', translated: 'He is selling his car.', conjugations: { present: 'sælger', past: 'solgte', perfect: 'solgt' } },
            'spørge': { en: 'to ask', example: 'Han spørger mig om vej.', translated: 'He is asking me for directions.', conjugations: { present: 'spørger', past: 'spurgte', perfect: 'spurgt' } },
            'svare': { en: 'to answer', example: 'Jeg svarer på spørgsmålet.', translated: 'I am answering the question.', conjugations: { present: 'svarer', past: 'svarede', perfect: 'svaret' } }
        },
        adjectives: {
            'ny': { en: 'new', example: 'Vi har een ny bil.', translated: 'We have a new car.' },
            'gammel': { en: 'old', example: 'Bogen er gammel.', translated: 'The book is old.' },
            'smuk': { en: 'beautiful', example: 'Det er en smuk dag.', translated: 'It is a beautiful day.' },
            'billig': { en: 'cheap', example: 'Bilen er billig.', translated: 'The car is cheap.' },
            'dyr': { en: 'expensive', example: 'Det er een dyr taske.', translated: 'It is an expensive bag.' },
            'varm': { en: 'warm', example: 'Vejret er varmt.', translated: 'The weather is warm.' },
            'kold': { en: 'cold', example: 'Vandet er koldt.', translated: 'The water is cold.' }
        },
        other: {
            'fordi': { en: 'because', example: 'Jeg er glad, fordi jeg har ferie.', translated: 'I am happy because I have vacation.' },
            'men': { en: 'but', example: 'Jeg er træt, men glad.', translated: 'I am tired, but happy.' },
            'også': { en: 'also', example: 'Jeg taler også dansk.', translated: 'I also speak Danish.' },
            'måske': { en: 'maybe', example: 'Måske kommer han senere.', translated: 'Maybe he will come later.' },
            'altid': { en: 'always', example: 'Han er altid glad.', translated: 'He is always happy.' },
            'aldrig': { en: 'never', example: 'Jeg spiser aldrig æbler.', translated: 'I never eat apples.' },
            'nogle gange': { en: 'sometimes', example: 'Jeg løber nogle gange.', translated: 'Sometimes I run.' },
            'hvem': { en: 'who', example: 'Hvem er det?', translated: 'Who is it?' },
            'hvorfor': { en: 'why', example: 'Hvorfor er du her?', translated: 'Why are you here?' }
        }
    },
    B1: {
        nouns: {
            'uddannelse': { en: 'education', example: 'Uddannelse er vigtig.', translated: 'Education is important.' },
            'mulighed': { en: 'opportunity', example: 'Der er mange muligheder.', translated: 'There are many opportunities.' },
            'samfund': { et: 'society', example: 'Vi lever i et moderne samfund.', translated: 'We live in a modern society.' },
            'fremtid': { en: 'future', example: 'Fremtiden ser lys ud.', translated: 'The future looks bright.' },
            'mening': { et: 'opinion', example: 'Hvad er din mening?', translated: 'What is your opinion?' },
            'miljø': { et: 'environment', example: 'Vi skal beskytte miljøet.', translated: 'We must protect the environment.' },
            'sundhed': { en: 'health', example: 'Sundhed er vigtig for alle.', translated: 'Health is important for everyone.' }
        },
        verbs: {
            'studere': { en: 'to study', example: 'Han studerer økonomi.', translated: 'He is studying economics.', conjugations: { present: 'studerer', past: 'studerede', perfect: 'studeret' } },
            'udvikle': { en: 'to develop', example: 'Teknologien udvikler sig hurtigt.', translated: 'Technology is developing fast.', conjugations: { present: 'udvikler', past: 'udviklede', perfect: 'udviklet' } },
            'diskutere': { en: 'to discuss', example: 'Vi diskuterer politik.', translated: 'We are discussing politics.', conjugations: { present: 'diskuterer', past: 'diskuterede', perfect: 'diskuteret' } },
            'forklare': { en: 'to explain', example: 'Læreren forklarer grammatik.', translated: 'The teacher is explaining grammar.', conjugations: { present: 'forklarer', past: 'forklarede', perfect: 'forklaret' } },
            'foreslå': { en: 'to suggest', example: 'Jeg foreslår en løsning.', translated: 'I suggest a solution.', conjugations: { present: 'foreslår', past: 'foreslog', perfect: 'foreslået' } },
            'beslutte': { en: 'to decide', example: 'Vi beslutter os for at rejse.', translated: 'We decide to travel.', conjugations: { present: 'beslutter', past: 'besluttede', perfect: 'besluttet' } }
        },
        adjectives: {
            'vigtig': { en: 'important', example: 'Det er en vigtig besked.', translated: 'It is an important message.' },
            'interessant': { en: 'interesting', example: 'Bogen er meget interessant.', translated: 'The book is very interesting.' },
            'nødvendig': { en: 'necessary', example: 'Det er nødvendigt at lære.', translated: 'It is necessary to learn.' },
            'forskellig': { en: 'different', example: 'De har forskellige meninger.', translated: 'They have different opinions.' },
            'politisk': { en: 'political', example: 'Det er en politisk diskussion.', translated: 'It is a political discussion.' },
            'social': { en: 'social', example: 'Hun har et stort socialt netværk.', translated: 'She has a large social network.' }
        },
        other: {
            'selvom': { en: 'although', example: 'Han smiler, selvom han er træt.', translated: 'He is smiling although he is tired.' },
            'derfor': { en: 'therefore', example: 'Det regner, derfor bliver vi inde.', translated: 'It is raining, therefore we are staying inside.' },
            'alligevel': { en: 'anyway', example: 'Det er dyrt, men jeg køber det alligevel.', translated: 'It is expensive, but I will buy it anyway.' },
            'desuden': { en: 'besides', example: 'Jeg er træt, desuden skal jeg tidligt op.', translated: 'I am tired, besides I have to wake up early.' },
            'for eksempel': { en: 'for example', example: 'Vi spiser meget, for eksempel ost.', translated: 'We eat a lot, for example cheese.' }
        }
    },
    B2: {
        nouns: {
            'udfordring': { en: 'challenge', example: 'Det er en stor udfordring.', translated: 'It is a big challenge.' },
            'ansvar': { et: 'responsibility', example: 'Han tager sit ansvar alvorligt.', translated: 'He takes his responsibility seriously.' },
            'økonomi': { en: 'economy', example: 'Landets økonomi vokser.', translated: 'The country\'s economy is growing.' },
            'kultur': { en: 'culture', example: 'Jeg studerer dansk kultur.', translated: 'I am studying Danish culture.' },
            'lovgivning': { en: 'legislation', example: 'Ny lovgivning er nødvendig.', translated: 'New legislation is necessary.' },
            'forudsætning': { en: 'prerequisite', example: 'En god uddannelse er en forudsætning.', translated: 'A good education is a prerequisite.' },
            'samfund': { et: 'society', example: 'Vi lever i et moderne samfund.', translated: 'We live in a modern society.' },
            'virksomhed': { en: 'company', example: 'Virksomheden vokser hurtigt.', translated: 'The company is growing fast.' },
            'forhold': { et: 'relationship/condition', example: 'Der er gode forhold på arbejdspladsen.', translated: 'There are good conditions at the workplace.' },
            'afdeling': { en: 'department', example: 'Jeg arbejder i en ny afdeling.', translated: 'I work in a new department.' },
            'udvikling': { et: 'development', example: 'Udviklingen går hurtigt.', translated: 'The development is happening fast.' },
            'forskning': { en: 'research', example: 'Forskning er vigtig for fremskridt.', translated: 'Research is important for progress.' },
            'uddannelse': { en: 'education', example: 'Uddannelse er nøglen til succes.', translated: 'Education is the key to success.' },
            'beskæftigelse': { en: 'employment', example: 'Beskæftigelsen stiger.', translated: 'Employment is increasing.' },
            'miljø': { et: 'environment', example: 'Vi skal beskytte miljøet.', translated: 'We must protect the environment.' },
            'sundhed': { en: 'health', example: 'Sundhed er vigtig for alle.', translated: 'Health is important for everyone.' },
            'politik': { en: 'politics', example: 'Politik påvirker vores liv.', translated: 'Politics affects our life.' },
            'teknologi': { en: 'technology', example: 'Teknologi ændrer samfundet.', translated: 'Technology is changing society.' },
            'kommunikation': { en: 'communication', example: 'God kommunikation er vigtig.', translated: 'Good communication is important.' },
            'sprog': { et: 'language', example: 'Dansk er et smukt sprog.', translated: 'Danish is a beautiful language.' },
            'samarbejde': { et: 'cooperation', example: 'Samarbejde skaber resultater.', translated: 'Cooperation creates results.' },
            'løsning': { en: 'solution', example: 'Vi fandt en god løsning.', translated: 'We found a good solution.' },
            'mål': { et: 'goal', example: 'Mit mål er at blive flydende.', translated: 'My goal is to become fluent.' },
            'resultat': { et: 'result', example: 'Resultatet var tilfredsstillende.', translated: 'The result was satisfactory.' },
            'beslutning': { en: 'decision', example: 'Beslutningen blev truffet i går.', translated: 'The decision was made yesterday.' },
            'erfaring': { en: 'experience', example: 'Han har mange års erfaring.', translated: 'He has many years of experience.' },
            'fremtid': { en: 'future', example: 'Fremtiden ser lys ud.', translated: 'The future looks bright.' },
            'fortid': { en: 'past', example: 'Fortiden påvirker nutiden.', translated: 'The past affects the present.' },
            'nutid': { en: 'present', example: 'Nutiden er vigtig.', translated: 'The present is important.' },
            'viden': { en: 'knowledge', example: 'Viden er magt.', translated: 'Knowledge is power.' },
            'forståelse': { en: 'understanding', example: 'Vi har en god forståelse.', translated: 'We have a good understanding.' },
            'information': { en: 'information', example: 'Informationen var klar.', translated: 'The information was clear.' },
            'diskussion': { en: 'discussion', example: 'Diskussionen var intens.', translated: 'The discussion was intense.' },
            'debat': { en: 'debate', example: 'Der var en livlig debat.', translated: 'There was a lively debate.' },
            'argument': { et: 'argument', example: 'Han fremlagde et godt argument.', translated: 'He presented a good argument.' },
            'perspektiv': { et: 'perspective', example: 'Et nyt perspektiv er vigtigt.', translated: 'A new perspective is important.' },
            'indflydelse': { en: 'influence', example: 'Han har stor indflydelse.', translated: 'He has a great influence.' },
            'tolerance': { en: 'tolerance', example: 'Tolerance skaber fred.', translated: 'Tolerance creates peace.' },
            'retfærdighed': { en: 'justice', example: 'Retfærdighed er vigtig i samfundet.', translated: 'Justice is important in society.' },
            'frihed': { en: 'freedom', example: 'Frihed er en grundlæggende rettighed.', translated: 'Freedom is a fundamental right.' },
            'lighed': { en: 'equality', example: 'Lighed er vigtig i demokratiet.', translated: 'Equality is important in a democracy.' },
            'rettighed': { en: 'right', example: 'Alle har rettigheder.', translated: 'Everyone has rights.' },
            'pligt': { en: 'duty', example: 'Det er vores pligt at hjælpe.', translated: 'It is our duty to help.' },
            'moral': { en: 'morality', example: 'Moral styrer vores handlinger.', translated: 'Morality governs our actions.' },
            'tro': { en: 'faith', example: 'Tro kan give håb.', translated: 'Faith can give hope.' },
            'religion': { en: 'religion', example: 'Religion spiller en rolle i kulturen.', translated: 'Religion plays a role in culture.' },
            'tradition': { en: 'tradition', example: 'Traditioner binder os sammen.', translated: 'Traditions unite us.' },
            'fest': { en: 'celebration', example: 'Vi holder en stor fest.', translated: 'We are having a big celebration.' },
            'kunst': { en: 'art', example: 'Kunst inspirerer mennesker.', translated: 'Art inspires people.' },
            'litteratur': { en: 'literature', example: 'Litteratur åbner sindet.', translated: 'Literature opens the mind.' },
            'musik': { en: 'music', example: 'Musik bringer glæde.', translated: 'Music brings joy.' },
            'film': { en: 'film', example: 'Vi så en god film.', translated: 'We saw a good film.' }
        },
        verbs: {
            'analysere': { en: 'to analyze', example: 'Vi analyserer data.', translated: 'We are analyzing data.', conjugations: { present: 'analyserer', past: 'analyserede', perfect: 'analyseret' } },
            'argumentere': { en: 'to argue', example: 'Han argumenterer for sin mening.', translated: 'He is arguing for his opinion.', conjugations: { present: 'argumenterer', past: 'argumenterede', perfect: 'argumenteret' } },
            'bidrage': { en: 'to contribute', example: 'Hun bidrager til projektet.', translated: 'She is contributing to the project.', conjugations: { present: 'bidrager', past: 'bidrog', perfect: 'bidraget' } },
            'overveje': { en: 'to consider', example: 'Vi overvejer at flytte.', translated: 'We are considering moving.', conjugations: { present: 'overvejer', past: 'overvejede', perfect: 'overvejet' } },
            'kritisere': { en: 'to criticize', example: 'Man kritiserer regeringens politik.', translated: 'One criticizes the government\'s politics.', conjugations: { present: 'kritiserer', past: 'kritiserede', perfect: 'kritiseret' } },
            'konkludere': { en: 'to conclude', example: 'Jeg konkluderer, at det er sandt.', translated: 'I conclude that it is true.', conjugations: { present: 'konkluderer', past: 'konkluderede', perfect: 'konkluderet' } }
        },
        adjectives: {
            'kompleks': { en: 'complex', example: 'Problemet er meget komplekst.', translated: 'The problem is very complex.' },
            'bæredygtig': { en: 'sustainable', example: 'Vi skal tænke bæredygtigt.', translated: 'We must think sustainably.' },
            'global': { en: 'global', example: 'Vi står over for globale problemer.', translated: 'We are facing global problems.' },
            'relevant': { en: 'relevant', example: 'Det er en relevant diskussion.', translated: 'It is a relevant discussion.' },
            'effektiv': { en: 'effective', example: 'Løsningen is effektiv.', translated: 'The solution is effective.' },
            'kontroversiel': { en: 'controversial', example: 'Emnet er kontroversielt.', translated: 'The topic is controversial.' }
        },
        other: {
            'imidlertid': { en: 'however', example: 'Jeg var træt, imidlertid fortsatte jeg.', translated: 'I was tired, however I continued.' },
            'derimod': { en: 'on the other hand', example: 'Han er rolig, derimod er hun nervøs.', translated: 'He is calm, on the other hand, she is nervous.' },
            'yderligere': { en: 'furthermore', example: 'Yderligere skal vi overveje prisen.', translated: 'Furthermore, we must consider the price.' },
            'i modsætning til': { en: 'in contrast to', example: 'I modsætning til mig, er hun meget glad.', translated: 'In contrast to me, she is very happy.' },
            'på grund af': { en: 'because of', example: 'Han kom for sent på grund af trafik.', translated: 'He was late because of traffic.' }
        }
    },
    C1:{
        nouns: {
            'afgørelse': { en: 'decision', example: 'Efter mange diskussioner nåede vi endelig en afgørelse om projektets retning.', translated: 'After many discussions we finally reached a decision about the project\'s direction.' },
            'behov': { et: 'need', example: 'Hun har et stort behov for anerkendelse.', translated: 'She has a great need for recognition.' },
            'erfaring': { en: 'experience', example: 'Hun har mange års erfaring inden for marketing.', translated: 'She has many years of experience in marketing.' },
            'fællesskab': { et: 'community', example: 'Fællesskabet i denne by er meget stærkt.', translated: 'The community in this town is very strong.' },
            'færdighed': { en: 'skill', example: 'Sprog er en vigtig færdighed i erhvervslivet.', translated: 'Language is an important skill in business.' },
            'forskning': { en: 'research', example: 'Forskningen viser nye resultater.', translated: 'The research shows new results.' },
            'forventning': { en: 'expectation', example: 'Der er store forventninger til den nye direktør.', translated: 'There are high expectations for the new director.' },
            'hensigt': { en: 'intention', example: 'Hensigten med dette møde er at diskutere fremtidige planer.', translated: 'The intention with this meeting is to discuss future plans.' },
            'indflydelse': { en: 'influence', example: 'Hans indflydelse på virksomheden har været betydelig.', translated: 'His influence on the company has been significant.' },
            'konsekvens': { en: 'consequence', example: 'En af konsekvenserne af hans handlinger var, at han mistede sit job.', translated: 'One of the consequences of his actions was that he lost his job.' },
            'ansvar': { et: 'responsibility', example: 'Det er dit ansvar at møde op til tiden.', translated: 'It is your responsibility to show up on time.' },
            'betingelse': { en: 'condition', example: 'En af betingelserne for ansættelsen er relevant erfaring.', translated: 'One of the conditions for employment is relevant experience.' },
            'egenskab': { en: 'characteristic', example: 'Tålmodighed er en værdifuld egenskab.', translated: 'Patience is a valuable characteristic.' },
            'formål': { et: 'purpose', example: 'Formålet med projektet er at reducere CO₂-udledningen.', translated: 'The purpose of the project is to reduce CO₂ emissions.' },
            'frihed': { en: 'freedom', example: 'Frihed er en grundlæggende menneskerettighed.', translated: 'Freedom is a fundamental human right.' },
            'grundlag': { et: 'basis', example: 'Beslutningen blev taget på et solidt grundlag.', translated: 'The decision was made on a solid basis.' },
            'indsats': { en: 'effort', example: 'Hun lagde en stor indsats i arbejdet.', translated: 'She put a great effort into the work.' },
            'nødvendighed': { en: 'necessity', example: 'Vand er een biologisk nødvendighed.', translated: 'Water is a biological necessity.' },
            'oplevelse': { en: 'experience (event)', example: 'Det var en uforglemmelig oplevelse.', translated: 'It was an unforgettable experience.' },
            'tilstand': { en: 'condition', example: 'Patientens tilstand er stabil.', translated: 'The patient\'s condition is stable.' },
            'aftale': { en: 'agreement', example: 'Vi indgik en aftale om samarbejde.', translated: 'We entered into an agreement on collaboration.' },
            'ansættelse': { en: 'employment', example: 'Hans ansættelse startede i januar.', translated: 'His employment started in January.' },
            'forhandling': { en: 'negotiation', example: 'Forhandlingerne var vanskelige.', translated: 'The negotiations were difficult.' },
            'konkurrence': { en: 'competition', example: 'Konkurrencen på markedet er hård.', translated: 'The competition in the market is tough.' },
            'løsningsforslag': { en: 'solution proposal', example: 'Vi præsenterede et nyt løsningsforslag.', translated: 'We presented a new solution proposal.' },
            'mål': { et: 'goal', example: 'Mit mål er at lære dansk flydende.', translated: 'My goal is to learn Danish fluently.' },
            'præstation': { en: 'performance', example: 'Hun leverede en imponerende præstation.', translated: 'She delivered an impressive performance.' },
            'projekt': { et: 'project', example: 'Projektet blev afsluttet til tiden.', translated: 'The project was completed on time.' },
            'strategi': { en: 'strategy', example: 'Virksomheden har en klar strategi for vækst.', translated: 'The company has a clear strategy for growth.' },
            'udfordring': { en: 'challenge', example: 'Det var en stor udfordring at gennemføre opgaven.', translated: 'It was a big challenge to carry out the task.' },
            'adfærd': { en: 'behavior', example: 'Hans adfærd var uacceptabel.', translated: 'His behavior was unacceptable.' },
            'fælles': { en: 'common', example: 'Vi har et fælles mål.', translated: 'We have a common goal.' },
            'indtryk': { et: 'impression', example: 'Hun gjorde et godt indtryk ved samtalen.', translated: 'She made a good impression at the interview.' },
            'kulturarv': { en: 'cultural heritage', example: 'Vi skal beskytte vores kulturarv.', translated: 'We must protect our cultural heritage.' },
            'medborger': { en: 'fellow citizen', example: 'Som medborger har du ansvar for at stemme.', translated: 'As a citizen, you have a responsibility to vote.' },
            'menneskerettigheder': { en: 'human rights', example: 'Menneskerettighederne skal respekteres af alle.', translated: 'Human rights must be respected by everyone.' },
            'sammenhæng': { en: 'context', example: 'I denne sammenhæng giver det mening.', translated: 'In this context, it makes sense.' },
            'samarbejde': { et: 'collaboration', example: 'Projektet kræver samarbejde mellem flere afdelinger.', translated: 'The project requires collaboration between several departments.' },
            'samfund': { et: 'society', example: 'Et velfungerende samfund bygger på tillid.', translated: 'A well-functioning society is built on trust.' },
            'tolerance': { en: 'tolerance', example: 'Tolerance er vigtigt i et multikulturelt samfund.', translated: 'Tolerance is important in a multicultural society.' }
        },
        verbs: {
            'analysere': { en: 'to analyze', example: 'Vi analyserer data.', translated: 'We are analyzing data.', conjugations: { present: 'analyserer', past: 'analyserede', perfect: 'analyseret' } },
            'argumentere': { en: 'to argue', example: 'Han argumenterer for sin mening.', translated: 'He is arguing for his opinion.', conjugations: { present: 'argumenterer', past: 'argumenterede', perfect: 'argumenteret' } },
            'bidrage': { en: 'to contribute', example: 'Hun bidrager til projektet.', translated: 'She is contributing to the project.', conjugations: { present: 'bidrager', past: 'bidrog', perfect: 'bidraget' } },
            'overveje': { en: 'to consider', example: 'Vi overvejer at flytte.', translated: 'We are considering moving.', conjugations: { present: 'overvejer', past: 'overvejede', perfect: 'overvejet' } },
            'kritisere': { en: 'to criticize', example: 'Man kritiserer regeringens politik.', translated: 'One criticizes the government\'s politics.', conjugations: { present: 'kritiserer', past: 'kritiserede', perfect: 'kritiseret' } },
            'konkludere': { en: 'to conclude', example: 'Jeg konkluderer, at det er sandt.', translated: 'I conclude that it is true.', conjugations: { present: 'konkluderer', past: 'konkluderede', perfect: 'konkluderet' } }
        },
        adjectives: {
            'kompleks': { en: 'complex', example: 'Problemet er meget komplekst.', translated: 'The problem is very complex.' },
            'bæredygtig': { en: 'sustainable', example: 'Vi skal tænke bæredygtigt.', translated: 'We must think sustainably.' },
            'global': { en: 'global', example: 'Vi står over for globale problemer.', translated: 'We are facing global problems.' },
            'relevant': { en: 'relevant', example: 'Det er en relevant diskussion.', translated: 'It is a relevant discussion.' },
            'effektiv': { en: 'effective', example: 'Løsningen is effektiv.', translated: 'The solution is effective.' },
            'kontroversiel': { en: 'controversial', example: 'Emnet er kontroversielt.', translated: 'The topic is controversial.' }
        },
        other: {
            'imidlertid': { en: 'however', example: 'Jeg var træt, imidlertid fortsatte jeg.', translated: 'I was tired, however I continued.' },
            'derimod': { en: 'on the other hand', example: 'Han er rolig, derimod er hun nervøs.', translated: 'He is calm, on the other hand, she is nervous.' },
            'yderligere': { en: 'furthermore', example: 'Yderligere skal vi overveje prisen.', translated: 'Furthermore, we must consider the price.' },
            'i modsætning til': { en: 'in contrast to', example: 'I modsætning til mig, er hun meget glad.', translated: 'In contrast to me, she is very happy.' },
            'på grund af': { en: 'because of', example: 'Han kom for sent på grund af trafik.', translated: 'He was late because of traffic.' }
        }
    },
    C2: {
        nouns: {
            'paradigmeskift': { et: 'paradigm shift', example: 'Et paradigmeskift ændrede videnskaben.', translated: 'A paradigm shift changed science.' },
            'diskurs': { en: 'discourse', example: 'Den politiske diskurs er skarp.', translated: 'The political discourse is sharp.' },
            'suverænitet': { en: 'sovereignty', example: 'Danmark har fuld suverænitet.', translated: 'Denmark has full sovereignty.' },
            'metafysik': { en: 'metaphysics', example: 'Metafysik er et komplekst emne.', translated: 'Metaphysics is a complex topic.' },
            'epistemologi': { en: 'epistemology', example: 'Epistemologi studerer viden.', translated: 'Epistemology studies knowledge.' },
            'udfordring': { en: 'challenge', example: 'Livet er fuld af udfordringer.', translated: 'Life is full of challenges.' },
            'forståelse': { en: 'understanding', example: 'Hans forståelse af emnet er dyb.', translated: 'His understanding of the topic is deep.' },
            'forventning': { en: 'expectation', example: 'Mine forventninger var høje.', translated: 'My expectations were high.' },
            'indflydelse': { en: 'influence', example: 'Hun har stor indflydelse i branchen.', translated: 'She has a great influence in the industry.' },
            'strategi': { en: 'strategy', example: 'Vi skal udvikle en ny strategi.', translated: 'We must develop a new strategy.' },
            'forpligtelse': { en: 'commitment', example: 'Jeg har en forpligtelse til mit arbejde.', translated: 'I have a commitment to my work.' },
            'perspektiv': { et: 'perspective', example: 'Vi skal overveje forskellige perspektiver.', translated: 'We must consider different perspectives.' },
            'vurdering': { en: 'assessment', example: 'Vi skal foretage en vurdering af situationen.', translated: 'We must make an assessment of the situation.' },
            'tilpasning': { en: 'adaptation', example: 'Tilpasning til nye omgivelser kan være svær.', translated: 'Adapting to new surroundings can be difficult.' },
            'indsats': { en: 'effort', example: 'Din indsats er værdsat.', translated: 'Your effort is appreciated.' },
            'engagement': { et: 'engagement', example: 'Hans engagement i projektet er bemærkelsesværdigt.', translated: 'His engagement in the project is remarkable.' },
            'analyse': { et: 'analysis', example: 'Vi skal lave en grundig analyse.', translated: 'We must do a thorough analysis.' },
            'integration': { en: 'integration', example: 'Integration af nye systemer er en kompleks proces.', translated: 'Integration of new systems is a complex process.' }
        },
        verbs: {
            'abstrahere': { en: 'to abstract', example: 'Han abstraherer fra de konkrete detaljer.', translated: 'He abstracts from the concrete details.', conjugations: { present: 'abstraherer', past: 'abstraherede', perfect: 'abstraheret' } },
            'artikulere': { en: 'to articulate', example: 'Han formåede at artikulere sin pointe klart.', translated: 'He managed to articulate his point clearly.', conjugations: { present: 'artikulerer', past: 'artikulerede', perfect: 'artikuleret' } },
            'legitimere': { en: 'to legitimize', example: 'Beslutningen blev legitimeret af folkeafstemningen.', translated: 'The decision was legitimized by the referendum.', conjugations: { present: 'legitimerer', past: 'legitimerede', perfect: 'legitimeret' } },
            'syntetisere': { en: 'to synthesize', example: 'Hun kunne syntetisere komplekse ideer i et enkelt argument.', translated: 'She could synthesize complex ideas into a simple argument.', conjugations: { present: 'syntetiserer', past: 'syntetiserede', perfect: 'syntetiseret' } },
            'dechifrere': { en: 'to decipher', example: 'Det tog lang tid at dechifrere den gamle kode.', translated: 'It took a long time to decipher the old code.', conjugations: { present: 'dechifrerer', past: 'dechifrerede', perfect: 'dechifreret' } },
            'internalisere': { en: 'to internalize', example: 'Han har internaliseret kritikken og ændret sin adfærd.', translated: 'He has internalized the criticism and changed his behavior.', conjugations: { present: 'internaliserer', past: 'internaliserede', perfect: 'internaliseret' } },
            'proliferere': { en: 'to proliferate', example: 'Problemerne begyndte at proliferere hurtigt.', translated: 'The problems began to proliferate quickly.', conjugations: { present: 'prolifererer', past: 'prolifererede', perfect: 'prolifereret' } },
            'belyse': { en: 'to illuminate', example: 'Undersøgelsen belyser et nyt aspekt af problemet.', translated: 'The study illuminates a new aspect of the problem.', conjugations: { present: 'belyser', past: 'belyste', perfect: 'belyst' } },
            'evaluere': { en: 'to evaluate', example: 'Vi evaluerer projektets resultater.', translated: 'We are evaluating the project\'s results.', conjugations: { present: 'evaluerer', past: 'evaluerede', perfect: 'evalueret' } },
            'implicere': { en: 'to imply', example: 'Dit udsagn implicerer, at du er uenig.', translated: 'Your statement implies that you disagree.', conjugations: { present: 'implicerer', past: 'implicerede', perfect: 'impliceret' } },
            'reflektere': { en: 'to reflect', example: 'Han reflekterer over sin rolle i virksomheden.', translated: 'He reflects on his role in the company.', conjugations: { present: 'reflekterer', past: 'reflekterede', perfect: 'reflekteret' } },
            'specificere': { en: 'to specify', example: 'Kan du specificere, hvad du mener?', translated: 'Can you specify what you mean?', conjugations: { present: 'specificerer', past: 'specificerede', perfect: 'specificeret' } },
            'understrege': { en: 'to emphasize', example: 'Taleren understreger vigtigheden af uddannelse.', translated: 'The speaker emphasizes the importance of education.', conjugations: { present: 'understreger', past: 'understregede', perfect: 'understreget' } }
        },
        adjectives: {
            'ambivalent': { en: 'ambivalent', example: 'Jeg er ambivalent over for forslaget.', translated: 'I am ambivalent about the proposal.' },
            'analytisk': { en: 'analytical', example: 'Han har en meget analytisk tilgang.', translated: 'He has a very analytical approach.' },
            'autonom': { en: 'autonomous', example: 'Hun er en autonom medarbejder.', translated: 'She is an autonomous employee.' },
            'essentiel': { en: 'essential', example: 'Tillid er en essentiel del af et forhold.', translated: 'Trust is an essential part of a relationship.' },
            'hypotetisk': { en: 'hypothetical', example: 'Vi taler kun om et hypotetisk scenarie.', translated: 'We are only talking about a hypothetical scenario.' },
            'inherent': { en: 'inherent', example: 'Der er en inherent risiko i projektet.', translated: 'There is an inherent risk in the project.' },
            'kritisk': { en: 'critical', example: 'Hans kritiske analyse er imponerende.', translated: 'His critical analysis is impressive.' },
            'nuanceret': { en: 'nuanced', example: 'Hun gav et nuanceret svar.', translated: 'She gave a nuanced answer.' }
        }
    }
};

export default vocabulary;
